name: Autograding Tests
on:
  push:
  repository_dispatch:
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Cliente Angular
      run: npm install -g @angular/cli@17
    - name: Instalação de dependências
      working-directory: sgcmapp/
      run: npm install
    - name: Teste Geral
      id: teste-geral
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Teste Geral
        setup-command: ''
        command: cd sgcmapp && ng test --no-watch --browsers ChromeHeadless
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTE-GERAL_RESULTS: "${{steps.teste-geral.outputs.result}}"
      with:
        runners: teste-geral
